### ISSUE TITLE
Fresh Install

### ISSUE THREAD

**Issue by powermx** [NzrlAfndi/Ichigo-Kurosaki#17]
root@Arcane:~/Ichigo-Kurosaki# node .
/root/Ichigo-Kurosaki/connect/index.js:21
const { state, saveState } = useSingleFileAuthState(`./${global.sessionName}.json`)
                             ^

TypeError: useSingleFileAuthState is not a function
    at Object.<anonymous> (/root/Ichigo-Kurosaki/connect/index.js:21:30)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)
    at node:internal/main/run_main_module:17:47
root@Arcane:~/Ichigo-Kurosaki# npm run dev

> ichigo-kurosaki@1.0.0 dev
> nodemon app.js

/root/Ichigo-Kurosaki/node_modules/nodemon/bin/nodemon.js:15
  require('update-notifier')({ pkg }).notify();
  ^

Error [ERR_REQUIRE_ESM]: require() of ES Module /root/Ichigo-Kurosaki/node_modules/update-notifier/index.js from /root/Ichigo-Kurosaki/node_modules/nodemon/bin/nodemon.js not supported.
Instead change the require of index.js in /root/Ichigo-Kurosaki/node_modules/nodemon/bin/nodemon.js to a dynamic import() which is available in all CommonJS modules.
    at Object.<anonymous> (/root/Ichigo-Kurosaki/node_modules/nodemon/bin/nodemon.js:15:3) {
  code: 'ERR_REQUIRE_ESM'
}
root@Arcane:~/Ichigo-Kurosaki#

**Comment by NzrlAfndi** [comment]
@FERDIZ-afk tau kah? Prasaan kita gaada error' lagi bagian connect/index.js

**Comment by DeadEyez1** [comment]
yarn add @adiwajshing/baileys
or yarn

Work for me

**Comment by NzrlAfndi** [comment]
> yarn add @adiwajshing/baileys or yarn
> 
> Work for me

Thanks for the answer
